### ISSUE TITLE
Not able to connect after using invite link

### ISSUE THREAD

**Issue by developerrahulofficial** [aryan-mehrabi/listen-together#1]
here is the screenrecording of my friend i sent the invite link

https://github.com/user-attachments/assets/7d755a7f-0555-4ad3-93d0-eed4dd10de4c

**Comment by aryan-mehrabi** [comment]
@developerrahulofficial 

Thank you for opening this issue and providing enough information.
I could replicate this issue and I'll fix it as soon as possible.
Also any PR is welcomed!!

Thanks,
Aryan.
